
export default function products(req, res) {
  res.status(200).json(
    [
      {
        id:1,
        img:'/assets/images/shop/22.jpg',
        title:'Wooden container Bowl',
        rating:'4.5',
        reviews:32,
        price:'143.00',
        piece_available:136,
        days_left:'28',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['gray','green','red','yellow','purple'],
        related_images:[
          '/assets/images/shop/22.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Winter Collections',
        sizes:['M','L','XL','XXL'],
        popular:true,
      },
      {
        id:2,
        img:'/assets/images/shop/23.jpg',
        title:'Jeff Gothelf learn UX',
        rating:'4.8',
        reviews:35,
        price:'120.00',
        piece_available:99,
        days_left:'22',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['red','yellow'],
        related_images:[
          '/assets/images/shop/23.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Woman',
        sizes:['XL','XXL'],
        popular:true,
        new:true,
      },
      {
        id:3,
        img:'/assets/images/shop/19.jpg',
        title:'The Pride and Prejudice',
        rating:'5.0',
        reviews:28,
        price:'180.00',
        piece_available:80,
        days_left:'15',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['green','purple'],
        related_images:[
          '/assets/images/shop/19.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Men',
        sizes:['M','L'],
        trending:true,
      },
      {
        id:4,
        img:'/assets/images/shop/20.jpg',
        title:'Hard Luck learn UX',
        rating:'4.0',
        reviews:20,
        price:'210.00',
        piece_available:139,
        days_left:'36',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['yellow','gray'],
        related_images:[
          '/assets/images/shop/20.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Groming',
        sizes:['L','XL'],
        popular:true,
      },
      {
        id:5,
        img:'/assets/images/shop/21.jpg',
        title:'The Little Prince',
        rating:'4.0',
        reviews:21,
        price:'230.00',
        piece_available:145,
        days_left:'42',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['green','red'],
        related_images:[
          '/assets/images/shop/21.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Electronics',
        sizes:['XL']
      },
      {
        id:6,
        img:'/assets/images/shop/18.jpg',
        title:'The Selfish Giant UX',
        rating:'4.0',
        reviews:25,
        price:'280.00',
        piece_available:65,
        days_left:'10',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['red','gray'],
        related_images:[
          '/assets/images/shop/18.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Winter Collections',
        sizes:['L'],
        popular:true,
        trending:true,
      },
      
      {
        id:7,
        img:'/assets/images/shop/1.jpg',
        title:'Little Women Shirt',
        rating:'5.0',
        reviews:32,
        price:'295.00',
        piece_available:55,
        days_left:'18',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['green','yellow','purple'],
        related_images:[
          '/assets/images/shop/1.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Woman',
        sizes:['L','XL','XXL'],
        new:true,
      },
      {
        id:8,
        img:'/assets/images/shop/2.jpg',
        title:'JFar From the Madding Crowd',
        rating:'4.8',
        reviews:35,
        price:'300.00',
        piece_available:68,
        days_left:'22',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['red','green','gray'],
        related_images:[
          '/assets/images/shop/2.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Men',
        sizes:['M','L','XL']
      },
      {
        id:9,
        img:'/assets/images/shop/3.jpg',
        title:'A Horseman in the Sky',
        rating:'4.7',
        reviews:50,
        price:'265.00',
        piece_available:70,
        days_left:'29',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['green','gray'],
        related_images:[
          '/assets/images/shop/3.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Winter Collections',
        sizes:['M','XXL']
      },
      {
        id:10,
        img:'/assets/images/shop/4.jpg',
        title:"Calvin Klein Women's",
        rating:'5.0',
        reviews:52,
        price:'208.00',
        piece_available:78,
        days_left:'35',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['gray','green'],
        related_images:[
          '/assets/images/shop/4.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Winter Collections',
        sizes:['M','L'],
        trending:true,
      },
      {
        id:11,
        img:'/assets/images/shop/5.jpg',
        title:"Adrianna Papell Women's",
        rating:'5.0',
        reviews:55,
        price:'198.00',
        piece_available:88,
        days_left:'09',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['gray','green','red'],
        related_images:[
          '/assets/images/shop/5.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Groming',
        sizes:['M','XL']
      },
      {
        id:12,
        img:'/assets/images/shop/6.jpg',
        title:"Big sale canvas basket",
        rating:'4.0',
        reviews:60,
        price:'188.00',
        piece_available:12,
        days_left:'36',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['gray','green','red','yellow'],
        related_images:[
          '/assets/images/shop/6.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Electronics',
        sizes:['L','XL','XXL']
      },
      {
        id:13,
        img:'/assets/images/shop/7.jpg',
        title:"Cotton Twill Suit",
        rating:'4.5',
        reviews:28,
        price:'240.00',
        piece_available:37,
        days_left:'20',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['red','yellow'],
        related_images:[
          '/assets/images/shop/7.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Woman',
        sizes:['M','L','XXL'],
        new:true,
      },
      {
        id:14,
        img:'/assets/images/shop/8.jpg',
        title:"Haggar Men's Heather",
        rating:'4.4',
        reviews:26,
        price:'260.00',
        piece_available:40,
        days_left:'30',
        summery:'Summer is the best time to stock up on lightweight bras keep cool. If your relaxing at home slip on a triangle bra.',
        colors:['gray','red'],
        related_images:[
          '/assets/images/shop/8.jpg',
          '/assets/images/shop/16.jpg',
          '/assets/images/shop/17.jpg',
        ],
        category:'Woman',
        sizes:['L','XXL'],
        new:true,
      },
    ]
  )
}